version: '3'
services:
  app:
    build: ./docker/go
    tty: true
    volumes:
      - .:/go/src/github.com/jackale/simple-webapp
    ports:
      - "5555:5555"
  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
